INSERT INTO Customers(code,name,address,phone,email) VALUES ('K26330201T','NISATEL SHPK','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K57621807D','ARIOL SHPK','FIER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K36608214T','AREN 2003 shpk','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K31512010F','BLEDAR TIRANA','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K49007111T','FLORA TEQJA','PEQIN',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K37508108O','ADELINA VESHI','KUCOVE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K32514054I','ADRITAIK AZIZOLLI','BERAT',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L56801206C','TANI GJIKONDI','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L13530601U','LICI PLUS','GJIROKASTER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('J69102521G','OMEGA CO SHPK','TEPELENE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L22617801P','HARMONIA HG SHPK','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K76626209I','RAPOS RESORT HOTEL','VLORE HIMARE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K56417201G','EKEZEJ SHPK','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K36813207V','ALBTURIST VLORE','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K72523402H','QENDRA SHENDETSORE NR2','FIER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K51726001P','ENOKLID BANA','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L51620020M','ADI CAPUNAJ','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L17315201P','GENTIAN SERJANAJ','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('J91825009L','XH & M SHPK','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K98406602O','MARGARITA SOLLAKU','LIBRAZHD',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L06620202I','STILIANO KANANI','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K61931005K','TRING TV  SHA','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K42808201K','VANGJEL SINANI','ELBASAN',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K82807005G','DASHNOR CJAPI','POBRAT',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K84011805I','SHPETIM SHANO','SARANDE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K82214002A','KELTION SHEHU','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L07623601S','KLODIAN NOFULLA','PRRENJAS',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K32510122D','MIHALLAQ KUMARAKU','BERAT',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K83414201L','NAZIM DERVISHI','ELBASAN',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K26330202E','VALONA KONSTRUKSION SHPK','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K49007115F','KLODJAN SINANI','ELBASAN',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K37810390V','PJETER MARKU','LAC',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L26507206U','KLEOLANDA KOKA','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L28006201K','MUSTAF SYLA','KUKES',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K34127411O','AGRON TITO','LUSHNJE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K82622206D','BULLARI 08','CERRIK',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K32513994Q','ALEKSANDER RUSI','KAVAJE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K41426038N','ELEKTRO MAGIC','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K63418207I','SHKELQIM KORCA','ELBASAN',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K46425203P','ARTAN GOXHAJ','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K36306820L','QANI KRYEMADHI','GRAMSH',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L59716401G','MALIQ MUSABELLIU','COROVOD, BERAT',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K82705207V','PERPARIM FRAKULLI','ELBASAN',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K87713502D','GJON SULI','LEZHE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K32509032W','DASHNOR KUCI','BERAT',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L47811101H','DANIEL BAHO','KUCOVE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K41502007F','ALUSH MUSTAFAJ','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L57312207G','ILIRJAN GABAJ','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K24005001H','GRAND KORCA','KORCE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L21414023U','ILIRIAN BANA','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K37506352D','AGUSTIN MALCI','LAC',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('J66702713Q','FLORIAN K','PESHKOPI',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L61405013S','GEZIM RRAKU','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K36527314C','KRENAR RUSTEMI','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L62512408A','VESEL FETAU','ROSKOVEC',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K37506802K','ISMAIL MYFTARAJ','BALLSH',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L67529801R','ISMAIL MYFTARAJ','BALLSH',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L67529801R','ARBAN MYFTARAJ','BALLSH',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K33110403F','GERDI LAZAJ','ROSKOVEC',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K63023201T','FATMIR TANUSHI','ELBASAN',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K32724202C','GEZIM DUNJA','ELBASAN',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K62206013S','LIRIE ALIA','KAMEZ',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K38706528E','ALTIN MUSTAFAJ','MEMALIAJ,TEPELENE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L32706001I','MERKO 2013','BERAT',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K33707843O','MARIANA JORGJI','SARANDE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K37510864H','LULJETA HYSENAJ','BALLSH',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L06306801D','ADELINA PALLOSHI','GRAMSH',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K93012402K','SHKELQIM BEJDAJ','FIER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L51313001I','JETON XHEKA','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L39706501G','LIRI HYSESANI','TEPELENE TEPELENE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K83700004U','ROMI QEMALI','KORCE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K37506114C','ANDIOL KOXHAJ','KUCOVE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K34122979K','KOSTA NIKA','SARANDE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L61710015A','ENKELEJDA SHEHU','TIRANE TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K23224402B','HIDRO SISTEM','FIER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K97117201D','COAST TO COAST','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K83204402V','KRIENKO GROUP SHPK','FIER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L04416801G','CRONY SR','TIRANE TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K41602074K','BENALB SHPK','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L07814602K','ARTUR QOSHKU','LIBRAZHD',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L53204204A','FLORENTINA HYSA','BELSH',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L42507406D','LEFTER ZANAJ','FIER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('J63229457L','SEGA SHPK','FIER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K32514914L','AGRON KUCI','KAVAJE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L52724403C','OLTI BRACE','FIER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L67505103J','MYSLIM FEKOLLARI','KUCOVE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K33910015F','EDUART MOLLA','KORCE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L43821402G','MIREL BEQIRI','LUSHNJE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K93505002M','EVIS XHAFA','URA VAJGURORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L01402035E','BAJRAM BABQORI','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L06405203E','JONIAN ZAIMI','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L52205521L','ASLLAN BEJA','DURRES',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L26605204U','SIDO SHPK','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L42926602V','ASQERI BUZHERI','GJIROKASTER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L66907205F','SILJANDO KANANI','HIMARE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K92928401P','FESTIM ZANAJ','FIER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L72615401J','PELLUMB SHEHAJ','FIER FIER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L03822403P','LINDITA CIKO','LUSHNJE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L02527405A','ILIR NUSHI','FIER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L03028406A','ENTON LAZAJ','ROSKOVEC',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L53025205P','AGIM ASLLANI','ELBASAN',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K38709215Q','LEONIDHA POPO','PERMET PERMET',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K38706516E','XHEMILE KORCA','KORCE KORCE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K32515893M','ISMET TATANI','DURRES DURRES',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L54529802S','KLODIAN LAPA','SARANDE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L12617001M','KLODIAN TOMANI','URA VAJGURORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('J93512436I','ARION SHPK','FIER FIER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K07924803N','SHENDELLIA SHPK','FIER FIER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K41517018D','ENKELEJDA HOXHA','TIRANE TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L64306403U','ARDIAN ALCANI','DIVJAKE DIVJAKE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K73025201H','ARTUR SULA','ELBASAN ELBASAN',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L19807101L','JULIAN TABAKU','PAJOVE,ELBASAN PAJOVE,ELBASAN',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('I44120804A','KLEMENT ZERAJ','SARANDE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K32513171W','BLEDIANA CIFLIKU','BERAT',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K32513841U','SHKELQIM GJINI','RROGOZHINE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K32620207T','SOKRAT CAKO','CERRIK',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('J96601219G','ENO SHPK','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K12915201W','IB SHELL GAS SHA','ELBASAN',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L11313023L','MARIGLEN RECI','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K33709811K','THELLENXE HOXHA','SARANDE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L18705501U','JUSTIN KORCA','TEPELENE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K74130404E','FATOS CAKA','FIER SHEGAN',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K68229505A','NET CENTER','LEZHE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L62511408S','NIRDIANA LLUKAJ','ROSKOVEC',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L13601203I','BESA HYSA','BELSH',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K53001804O','VELI REXHEPI','KAVAJE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K43903402K','ARTAN ZHUPANI','LUSHNJE,GRADISHT',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K46601002T','ELEKTROTEK SHPK','SHKODER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('J73312239N','FIRMA TANAJ','ELBASAN',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L02512401H','ALBERT CEPELE','ROSKOVEC',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K38708295V','SOFOKLI PECI','PERMET PERMET',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L01403505S','MARIGLENT BOXHUFI','DURRES DURRES',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L41712009J','ALKETA BANA','KAMEZ KAMEZ',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L51715010G','GLOBE SHOPS','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L34308801M','SOKOL KRISTIANI','SARANDE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L54704005N','TASUL PACILI','KORCE KORCE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L67302204C','AGRON SINANAJ','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L54501022F','FERDINAND KODRA','KORCE KORCE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K21909002K','FOCUS MEDIA NEWS SHPK','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K34127410G','AIDA FASKAJ','LUSHNJE LUSHNJE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L03223402R','AFERDITA BREGASI','FIER FIER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L32902003K','ENO SERJANAJ','BERAT',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K33922033R','MARJETA OSMANI','KORCE KORCE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L06405004N','ENERIDA BERBERI','KORCE KORCE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K64801001P','RINIA SHPK','KORCE KORCE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K94508402H','PERPARIM CELA','LUSHNJE LUSHNJE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L04820001X','DAISY & ETM','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K94431401T','LALA COMPANY SHPK','CERREM ,LUSHNJE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('J73804662W','BREGU SHPK','POGRADEC',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K36309769F','ZUMA SHPK','PESHKOPI',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L42011023U','IUTE CREDIT ALBANIA SH.A','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L36310205A','RAIMONDA ALLIAJ','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K61719014M','MAJLINDA TORO','TIRANE TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K01711004F','ABC NEWS SH.A','TIRANE TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K73208020O','FLAMUR LULO','BERAT',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K51723038I','BASHKIA TIRANE','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('J71413001L','TV KLAN SHA','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K12007002U','TOP CHANNEL SHA','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('J67209233W','DREJTORIA VENDORE E POLICISE VLORE','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K32801450N','ZIJA FETAU','ROSKOVEC ROSKOVEC',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L52115062S','EDION BRAHO','TIRANE TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K72627402H','BOSHNJAKU.B','FIER FIER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('J97426201K','FJORTES','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L64311802P','MAJLINDA KALEMI','BORSH BORSH',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L66816203I','ISIDOR  MUZAKA','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K68121808W','SHKELQIMI 07','LUSHNJE LUSHNJE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L43617401S','M&B WELLNESS','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L43803801B','LEDI CENE','SARANDE SARANDE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L66904219G','ADMIRIM BEGAJ','RADHIME RADHIME',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L54323807A','HALIM DACI','SARANDE SARANDE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L17204204E','2G-GLOBAL SERVICE OF MANAGMENT CONSULTANTS','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K36708202W','PELLUMB MEMUSHAJ','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L67207205J','EMPIRE BEACH RESORT','DHERMI DHERMI',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L46307207B','BUKUROSHE ZANAJ','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('J83211203F','KAPIDANI','KORCE KORCE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L12716002S','LUAN XHAFKOLLARI','BERAT BERAT',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L44224801V','GERALD KURTI','SARANDE SARANDE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K32801256D','SELAMI FRAKULLI','ELBASAN ELBASAN',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L26717201N','ELMIR VANGJELI','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K31510511K','MIHAL EKONIMI','DURRES',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K01414003D','MEDIA VIZION SHA','TIRANE TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L6880.3401M','ADRIATIK KALEMI','COROVOD, BERAT COROVOD,BERAT',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L76604205F','REDJAN SHABANAJ','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('J62903456H','GJIKURIA','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K73610001H','ASAN TARE','URA VAJGURORE URA VAJGURORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L42804405M','AGRON OIL','ROSKOVEC ROSKOVEC',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('J64103438M','LALA','DIVJAKE DIVJAKE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L16325205D','STUDIO DIAGNOSTIFIKUESE GEGA & QUARTA COLOSSO','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K12217003P','DREJTORIA E PERGJITHSHME E POLICISE SE SHTETIT','TIRANE TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L43310401U','HEKURAN VELIAJ','PATOS PATOS',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L21402022V','VALTER CACAJ','KAMEZ KAMEZ',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K14406405K','VILSON DHAMO','LUSHNJE LSHNJE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K82528204O','SHEFIKAT HYSA','BELSH BELSH',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K32510777W','FATOS SHEHU','GJIROKASTER GJIROKASTER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L74325801J','EDVIN HYSENI','SARANDE SARANDE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K34107810W','JONICA CONSTRUZIONI','SARANDE SARANDE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K77205201O','ALEKO SIMONI','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L61627026E','TRIUM COMMUNICATION SHPK','TIRANE   TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K36526254T','KRISTELA','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L73719004L','DORIAN MANO','KORCE KORCE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L44819001M','REDI ORGOCKA','KORCE KORCE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L76402202L','HERALD LEKAJ','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K36805202K','GJENERAL G','DHERMI DHERMI',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K36603503U','BALILI-KO','SARANDE SARANDE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L76406204B','EDMOND SHEHAJ','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L66820210L','ROBERT BEGO','RADHIME  RADHIME',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L42123022G','AIDA HOXHA','TIRANE  TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L64625802C','FERNANDO BRAHIMI','SARANDE SARANDE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K46605216V','SMERALD','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L77525801V','GENTJAN VELAJ','BALLSH BALLSH',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K93303201A','I.H. KALAJA & COMPANY','POGRADEC POGRADEC',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K83716009N','SUPERMARKET ELISABET SHPK','KORCE KORCE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L72819201A','EDUART HYSA','BELSH',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K73710404N','AVNI KAJA','DIVJAKE DIVJAKE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('J97511807W','CAUSHI','PEQIN PEQIN',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K64006804T','ARBEN HITO','SARANDE SARANDE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L43218401L','ANILA CERVANAKU','FIER FIER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L32923001H','ANTIPATREA HOTEL','BERAT BERAT',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L26602209A','MIHAL MECI','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K33709848S','AGIM ASLLANI','SARANDE SARANDE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L54403803I','DASHNOR VEIPI','SARANDE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L66828204H','BESNIK HARUNI','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K92303014R','SAIMIR KOLA','TIRANE TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L56306204T','ENTON LULO','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K87711101H','ANI VRUSHA','KUCOVE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L51307006S','B.O BEOLA','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K04005076C','OLKET SHPK','KORCE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K31528510A','AGI CENTER SHPK','DURRES',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K36309201H','BLU STAR SHPK','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K72217006A','BLEDAR ALHASA','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K37509371B','DELI RECI','LAC',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K63803616O','ZHANETA TONA','POGRADEC',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('J94316089N','LIRTON SHPK','KORCE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K01403504J','SHTARO SHPK','DURRES',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K83926804I','ADELINA RRAKU','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K33019863V','XHEMAL CIKALLESHI','KAVAJE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K83323404U','VALBONA SHEHAJ','FIER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L42412501O','EKO MARKET SHPK','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K41627008D','ARMEND DEDA','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K32512132C','PANDI CECA','BERAT',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K53929402D','NIKLOVAN CELA','LUSHNJE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K81322034I','KUJTIM MARASHI','TIRANE KAMEZ',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K86519006E','MEGA ELECTRO','SHKODER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L47529501U','XHARI ELEKTROSHTEPIAKE','LEZHE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('J62223004L','REXHINA SHPK','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L26804206O','GSM KLIMAIRE','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K51415506V','KADRIE CURRI','DURRES',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K83912402N','MIMOZA PRIFTI','DIVJAKE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K62715403D','JORGJI LLUKAJ','ROSKOVEC',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('J82916507H','SIMMONS EDECO LIMITED','FIER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L36713201R','EURO FRIGO 2013','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('J72124001N','MARKETING DISTRIBUTION','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K33710891K','ALEKSANDRA MITRO','SARANDE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L02805602B','ELEKTROSHTEPIAKE NOVI','GJIROKASTER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K38707175T','MYRTEZA SINANI','ELBASAN  PAJOVE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K61323006H','FIRDES DUKA','TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K74020402E','FLORENC KUBOLLI','LUSHNJE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K56321824F','AGIM DOLLANI','GRAMSH',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('I22105023O','INSTITUTI PROFESIONAL ATC','TIRANE TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L57017205G','GENESIS PROJECTING','TIRANE TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L64306803V','MIRELA LALA','BORSH BORSH',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L46307203P','JURGEN MELIKA','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L71517007P','NIK-MA','DHERMI DHERMI',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L76320203O','ELGERTO SERJANAJ','VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L56927215T','ENKELEJDA RUSHA','BORSH BORSH',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('J77520515P','XHOVANA SHPK','LEZHE LEZHE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K53904401I','ADRIATIK BRAHIMI','LUSHNJE LUSHNJE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K56703267M','QENDRA E ZHVILLIMIT PAK','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K83820804V','FLORA RUCI','SARANDE KSAMIL',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K92214505I','CEZAR DAKOLI','DURRES DURRES',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L77306202H','JETMIR GJYZARI','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L63115203A','NAIM DERVISHI','BELSH BELSH',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L36901204K','BELONA SERAJ','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L73928402B','OLSI GJECI','LUSHNJE LUSHNJE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K36419218I','INFOTECH SHPK','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L72211069N','UNIVERS CENTER','KAMEZ KAMEZ',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L44210804V','SERGEJ GOSHI','SARANDE SARANDE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L03720601V','ANIL ISMAILANJI','POGRADEC POGRADEC',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L26604203H','FISNIK MULLAJ','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('J94824810S','LAGJINI SA','SARANDE SARANDE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L53303226F','ERVIN MARISHTA','ELBASAN ELBASAN',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L56712601P','EURO MARKET FREAL','BILISHT BILISHT',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L66912201V','REIS ISLAMAJ','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K63012201K','FITIMTAR BULLARI','CERRIK CERRIK',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L61706045A','ELDI GJON','TIRANE TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L59425503S','PAVLINA NENI','TEPELENE TEPELENE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L43824803H','MARJUS HAMITI','SARANDE SARANDE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K32514625I','BESNIK SKENDULI','GJIROKASTER GJIROKASTER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L26402204A','LULZIM DEMO','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K67709507V','ALDEOS SHPK','LEZHE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L76402212S','GEZIM LILAJ','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K52609001V','LULEZIM BONI','BERAT BERAT',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L32217505S','MIRUSH LOCA','DURRES DURRES',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('J66703306O','AVDULI','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L47318201K','P.W.W','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L76718201A','ERGUST METAJ','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L26423205U','ARIEL MECAJ','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L27009201A','MIRJAM ISUFAJ','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L47122202J','VALBONA MECAJ','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K91410043U','GENIAL SHPK','TIRANE TIRTANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K37508668R','ADELINA LLESHI','LIBRAZHD LIBRAZHD',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K44628401F','MYZEGJENE KUBOLLI','DIVJAKE DIVJAKE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K62513403K','ARIAN ZANAJ','FIER FIER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L52115207F','DRITE KALOSHI','TIRANE TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L544140003P','AUREL PRIFTI','KORCE KORCE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L41308083I','DMAX EXPERT SHPK','TIRANE TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L61706045A','ELDI GJONI','TIRANE TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L63602406I','ROVENA ZANAJ','FIER FIER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K66527202W','JONUFRA - F','VLORE VLORE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L33806401O','ILIR ALCANI','DIVJAKE DIVJAKE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L22925402C','PESE VELLEZERIT','FIER FIER',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L03706003A','FATOS DENAS','KORCE KORCE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L73706803J','MIGENA ZERAJ','SARANDE SARANDE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K63801401O','ERION LALA','LUSHNJE LUSHNJE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('K82320007D','SPOT COMMUNICATIONS','TIRANE TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L11518009H','COMMERCEE CORP SHPK','TIRANE TIRANE',NULL,NULL);
INSERT INTO Customers(code,name,address,phone,email) VALUES ('L56621204L','ARBA SHIPPING AGENCY SHPK','VLORE',NULL,NULL);
