INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L16919202N','RAJMONDA OSMENI','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K86505205H','VIRON XHAFERI','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K63026404B','KOMBI SHPK','FIER','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K11308001B','ABCOM','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('J61826509U','A.T.H.S','DURRES','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K92201058S','MARES REKLAMA','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K92922201T','SITEL MOBILE SHPK','ELBASAN','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L04820001N','DAISY & ETM  PAJISJE FISKALE','KORCE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K26330201T','NISATEL SHPK','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('J62426002Q','INFOSOFT OFFICE SHPK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K36608208V','COLOMBO SHPK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('J92305001S','LINDA SHPK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('J61826508M','AL MAR SHPK','DURRES','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K91410043U','GENIAL SHPK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('J61820040I','DHL EXPRESS','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K13512401J','A.A.R SHPK  PANDELI RAJOHO','FIER','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('J61824053N','ALBTELECOM EAGLE MOBILE SHA','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K31602028G','ARBEN MALI','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K51731005D','RADIO LINK SHPK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K91314024I','PAJTONI SHPK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('J72124001N','MARKETING & DISTRIBUTION','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K71505003O','ORA NEWS SH.A','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K12007002U','TOP CHANNEL  SHPK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K61320001U','ESHREF DAKO','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K61808034U','GS1 ALBANIA','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K01417001C','ABISSNET SHA','KAVAJE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L51907030J','TOROS TRANSPORT','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K76409201O','LELI GROUP SHPK','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('J66703216P','TRIS ELEKTRIK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L02205042V','GLOBAL NET SHPK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L21822005F','CREATIVE SHPK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K16605201R','ARTEG','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L46419209L','GOLDEN EYE ELTON LILAJ','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K97226202M','SALIAJ TRANSPORT','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L06509205U','FLORIAN DURAJ AVOKAT','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K52814202D','RADIO KLEA','ELBASAN','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K4161418O','CELESI DESIGN&PUBLICITET','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K92801201D','ELBASAN TV','ELBASAN','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K72925208T','MERITAN HYSENI','ELBASAN','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K32712210C','KUMRIA 1','ELBASAN','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K83410201O','BAHITI G SHPK','ELBASAN','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('J61826012K','ALBA ELETTRICA','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L51711502C','GERNARD AGO','DURRES','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L37404701S','ERBA 2013','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K77219205A','ELDO 07','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L22126015N','JUR & CHRIS SHPK','TIRANE ,VORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K62303017P','FIT MEK OIL  SH.A','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K26307202E','AULONA POL 1 SHPK','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('J71413001L','TV KLAN SHA','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K91622016U','EPPC PARTNERS COSULTANAY','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K31624163S','JONA TRAVEL & TOURS','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L36713201R','EURO FRIGO 2013','VLORE,NOVOSELE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K01814501G','ALEKSI','DURRES','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('GB119234722','GPSG','TURQI ELVAN SOKAK NO:9/4 ULKER UNVER PLAZA','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K32627418M','KRASNIQI SA','FIER','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L51503017T','PRIUS SOLUTION SHPK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L21804002G','GO SHIPPING ALBANIA','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L42326503F','CMA CEM ALBANIA','DURRES','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K16619201S','EMILIANO-EURO SHPK','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K88010301S','SILVER SHPK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L66401201U','LASKA  AUDITIME','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L36405204P','KOVI ELEKTRIKE','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K53929402D','MIKLOVAN CELA','LUSHNJE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L36411204A','ARTAN BRAHIMAJ','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L46419209L','ELTON LILAJ','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L61516001H','DONIKA NDINI','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K22112005E','PANORAMA GROUP  SHA','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K46811001V','ALBAMEDIA','TIRANE TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L52310028T','4 K TRADING ALBANIA','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K31915018E','A&A SECUIRITY SURVEY','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K71821013S','DM CONSULTING SERVICES','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('J64103021R','BREGU SHA','KORCE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L51607030A','EBE SHIPPING CO','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L17224204M','RDA 11 SHPK','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K36518238L','ERALDO SHPK','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K52926201M','SITEL ALBANIA SHPK','ELBASAN','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('J61910048C','ARPIKO TRADE SHPK 2013','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K01414003D','MEDIA VIZION SHA','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K71818012S','CARTIDGE WORLD','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L56823202L','ALTIN DEROMEMAJ','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K36309201H','BLU STAR  SHPK','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L51328502G','VEZI GROUP','DURRES','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K81325001B','IMPACT SHPK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L46617201M','VULLNET AVDURAMANI','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K06426203P','FATMIR KONDO','VLORE VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L36401202C','MARTED HOXHAJ','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('J61824038Q','TRANSALBANIA SHPK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K58615301M','GENER 2 SHPK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L36518201N','A.M.L SHPK','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K46922202H','GIPS XHOVA DEKOR','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K66424202E','TUR COBO','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('J62903255K','KREKA SHPK','ELBASAN','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K11715005L','VODAFONE ALBANIA SHA','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L12510401V','BAJRAKTARI CONSTRUCTION SHPK','FIER','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K01711004F','ABC NEWS SHA','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K91808502Q','MERJA OUTLET SHPK','DURRES','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K97313202U','TISA TOURS  (MIKEL ZINXHIRIA)','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('J61827510G','DIAMANT','DURRES','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L12122018Q','SHQIPTARJA.COM','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L51817008H','MULTISCREEN','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K83410201O','BANIA - G','KAVAJE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K42416009V','LIRAS','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K46526058R','DANI SECURITY SHPK','SHKODER','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L22224014V','LOGICAL SHPK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K22829401K','ERA 2002 SHPK HOTEL PARTNER','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K16604201M','ANA 2001','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L5220844L','UNIK GROUP SHPK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L42108451O','PRO BASKET INVADERS','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L76620202P','FATMIR ABAZAJ','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L61523053B','ENERGREEN AD ANI MURATI','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K91608002D','IFT NOVA SHPK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L61627026E','TRIUM COMMUNICATIONS','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L57214206F','GENTJAN COBAJ','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K36708203M','ARBEN BELAJ','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L56306204T','ENTON LULO','VLORE VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L81318030D','ALPHA SOFT SHPK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L41818009T','AV MIRELA KRESHPA','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('J97426201K','FJORTES.shpk','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('J62904311H','HARD & SOFT PROFESIONAL SHPK','ELBASAN','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L37222206U','ERJON JAUPI','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('J61820049L','ITD SHPK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K61813020G','EUROBRANDS SHPK  (IMETEC ALBANIA)','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K72217008P','SALI ELEKTRIK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L01626012A','ORBICO SHPK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('J92211003P','DAJTI KONSTRUKSION','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('J77207216A','MEHILLAJ SHPK','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K33020403G','GEMAKLER SHPK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K31418036C','INFOSOFT SD SHPK  FINANCA 5','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K01809005G','TV BALLKAN  SHA    A1 REPORT','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K23323401N','MYRTO SECURITY','FIER','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K72410014H','OSHEE SHA','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('it00693740425','INDESIT COMPANY','ITALI, Viale aristide merloni  4760044 fabriano','3907326611','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K86526204M','LUCIANA LASKA','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K74526805F','PANAJOTI TRANSPORT','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('J72510483F','KERRI SHPK','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K36511217J','CAUSHI SHPK','VLORE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K11405004N','PLANET TELEVIZION SHA','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K71822801C','DIMAPAK SHPK','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('L22320101A','CAGATAY LOGISTICS ALBANIA','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('J72510447J','GORA FIER','FIER','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K22103001T','A & A INTERNATIONAL','TIRANE','','');
INSERT INTO Supplier(code,name,address,phone,email) VALUES ('K72223025M','ARB SECURITY','TIRANE','','');
