INSERT INTO Warehouse(`code`,`name`,`address`,`phone`) VALUES ('M1','AZA ELEKTROSHTEPIAKE','Vlore',NULL);
INSERT INTO Warehouse(`code`,`name`,`address`,`phone`) VALUES ('M5','DYQANI FIER','Rr. "Jakov Xoxa", Fier','034 50 4960');
INSERT INTO Warehouse(`code`,`name`,`address`,`phone`) VALUES ('M6','DYQANI TIRANE','Pajtoni Center, Tirane','042 45 3002');
INSERT INTO Warehouse(`code`,`name`,`address`,`phone`) VALUES ('M7','DYQANI ELBASAN','Qendra "Dardanët", Elbasan','054 51 4667');
INSERT INTO Warehouse(`code`,`name`,`address`,`phone`) VALUES ('M8','DYQANI KAVAJE','Blv. "Josif Budo", Kavaje','055 80 0766');
INSERT INTO Warehouse(`code`,`name`,`address`,`phone`) VALUES ('M9','DYQANI VLORE','Blv  Gjergj Kastrioti, Vlore','033 40 9931');
INSERT INTO Warehouse(`code`,`name`,`address`,`phone`) VALUES ('M10','DYQANI DURRES','Rr. "Adria", Durres','052 42 0428');
INSERT INTO Warehouse(`code`,`name`,`address`,`phone`) VALUES ('M11','DYQANI SHKODER','Rr. Qemal Draçini, Shkoder','022 80 2573');
INSERT INTO Warehouse(`code`,`name`,`address`,`phone`) VALUES ('M12','DYQANI TIRANE 2 SELVIA','Rr. e Dibres, Tirane','044 53 9060');
INSERT INTO Warehouse(`code`,`name`,`address`,`phone`) VALUES ('M13','DYQANI LUSHNJE','Shëtitorja e Palmave, Lushnje','035 70 4848');
INSERT INTO Warehouse(`code`,`name`,`address`,`phone`) VALUES ('M14','DYQANI KORCE','Blv. Fan Noli, Korce','082 24 4490');
INSERT INTO Warehouse(`code`,`name`,`address`,`phone`) VALUES ('M15','MAGAZINA SERVIS',NULL,NULL);
INSERT INTO Warehouse(`code`,`name`,`address`,`phone`) VALUES ('M16','MAGAZINA SHUMICE','Vlore',NULL);
